GM = GM or GAMEMODE

GM.DayZ_Items = {
	{
		ID		 = 	"item_money",
		Name		 = 	"Money",
		Angle		 =	Angle(0,0,0),
		Desc 		 = 	"Holla, Holla. Get dolla.",
		Model		 =  "models/props/cs_assault/money.mdl",
		Weight	     =  0,
		LootType 	 =  { "None" },
		SpawnChance  =  -1,
		SpawnOffset  =  Vector(0,0,3.5),
	},
	
	{
		ID 		 =  "item_credits",
		Name		 =  "Credits",
		Angle 		 =  Angle(0,0,0),
		Desc 		 =  "Your credits. Used to purchase perks/upgrades.",
		Model 		 =  "models/freeman/cyb_hexagon_small.mdl",
		Color 		 =  Color(41, 128, 185),
		Weight		 =  0,
		LootType	 =  { "None" },
		SpawnChance  =  -1,
		SpawnOffset  =  Vector(0,0,3.5),
	},
	
	{
		ID		 =  "item_chips",
		Name 		 =  "Chips",
		Angle		 =  Angle(0,0,0),
		Desc 		 =  "Your chips. Used primarily for gambling.",
		Model		 =  "models/amanda/poker_chip_blue.mdl",
		Color		 =  Color(41, 128, 185),
		Weight		 =  0,
		LootType	 =  { "None" },
		SpawnChance  =  -1,
		SpawnOffset  =  Vector(0,0,3.5),
	},
	
	{
		ID 		 =  "item_basebat",
		Name 		 =  "Baseball bat",
		Angle		 =  Angle(0,0,0),
		Desc		 =  "A metal bat with a wooden core.",
		Model		 =  "models/weapons/w_basebat.mdl",
		Weight		 =  10,
		LootType	 =  { "Weapon" },
		Price		 =  100,
		Credits		 =  10,	
		SpawnChance  =  40,
		Melee		 =  true,
		SpawnOffset	 =  Vector(0,0,0),
		Weapon		 =  "melee_bat_dayz",
		EatFunction	 =  function(ply, item) ply:EatHurt(5, 50) end,	
	},

	{
		ID 		 = "item_yamato",
		Name		 = "Yamato",
		Angle		 = Angle(0,0,0),
		Desc		 = "A sleek, tempered blade atop a stylish hilt.",
		Model		 = "models/tiggomods/dmc4/yamato.mdl",
		Weight 		 = 10,
		LootType	 = { "Weapon" },
		Price		 = 1525,
		Credits		 = 150,	
		SpawnChance  = 1,
		Melee		 = true,
		SpawnOffset	 = Vector(0,0,0),
		Weapon		 = "melee_yamato",	
		EatFunction  = function(ply, item) ply:EatHurt(5, 50) end,	
	},
	
	{
		ID = "item_bowie",
		Name = "Bowie Knife",
		Angle = Angle(0,0,0),
		Desc = "A knife used primarily in trenches.",
		Model = "models/bowie_knife.mdl",
		Weight = 10,
		LootType = { "Weapon" },
		Price = 525,
		Credits = 50,	
		SpawnChance = 15,
		Melee = true,
		SpawnOffset = Vector(0,0,0),
		Weapon = "melee_bowie",
		EatFunction = function(ply, item) ply:EatHurt(5, 50) end,	
	},

	{
		ID = "item_knife",
		Name = "Tactical Knife",
		Angle = Angle(0,0,0),
		Desc = "A knife for everyday use.",
		Model = "models/weapons/w_knife_t.mdl",
		Weight = 10,
		LootType = { "Weapon" },
		Price = 225,
		Credits = 25,	
		SpawnChance = 15,
		Melee = true,
		SpawnOffset = Vector(0,0,0),
		Weapon = "melee_knife",
		EatFunction = function(ply, item) ply:EatHurt(5, 50) end,	
	},
	
	{
		ID = "item_crowbar",
		Name = "Crowbar",
		Angle = Angle(0,0,0),
		Desc = "A multipurpose tool used for leverage.",
		Model = "models/weapons/w_crowbar.mdl",
		Weight = 10,
		LootType = { "Weapon" },
		Price = 110,
		Credits = 10,		
		SpawnChance = 40,
		Melee = true,
		SpawnOffset = Vector(0,0,0),
		Weapon = "melee_crowbar_dayz",
		EatFunction = function(ply, item) ply:EatHurt(5, 50) end,	
	},
	
	-- Edibles
	
	{
		ID = "item_drink1",
		Name = "Soda Can",
		Angle = Angle(0,0,0),
		Desc = "Drink this to quench your thirst.",
		Model = "models/props_junk/PopCan01a.mdl",
		Weight = 1,
		LootType = { "Food" },
		Price = 15,	
		Credits = 1,
		SpawnChance = 90,
		SpawnOffset = Vector(0,0,3.5),
		DrinkFunction = function(ply, item) ply:Drink(15) end,		
	},

	{
		ID = "item_water",
		Name = "Water Bottle",
		Angle = Angle(0,0,0),
		Desc = "Drink this to quench your thirst.",
		Model = "models/props/cs_office/Water_bottle.mdl",
		Weight = 1,
		LootType = { "Food" },
		Price = 25,	
		Credits = 2,
		SpawnChance = 60,
		SpawnOffset = Vector(0,0,4),
		DrinkFunction = function(ply, item) ply:Drink(35) end,		
	},

	{
		ID = "item_coffee",
		Name = "Coffee",
		Angle = Angle(0,0,0),
		Desc = "A little pick me up in the morning.",
		Model = "models/props_junk/garbage_coffeemug001a.mdl",
		Weight = 1,
		LootType = { "Food" },
		Price = 45,	
		Credits = 4,
		SpawnChance = 45, -- Out of 100
		SpawnOffset = Vector(0,0,3.5),
		DrinkFunction = function(ply, item) ply:Drink(5) ply:GiveStamina(15) end,		
	},	

	{
		ID = "item_shoe",
		Name = "A Shoe",
		Angle = Angle(0,0,0),
		Desc = "Tastes like cow.",
		Model = "models/props_junk/Shoe001a.mdl",
		Weight = 1,
		LootType = { "Basic" },
		Price = 15,	
		Credits = 1,
		SpawnChance = 55,
		SpawnOffset = Vector(0,0,4),
		UsedInCrafting = true,	
		EatFunction = function(ply, item) ply:EatHurt(5, 50) end,	
	},

	{
		ID = "item_gunpowder",
		Name = "Gunpowder",
		Angle = Angle(0,0,0),
		Desc = "A mixture of sulfur, charcoal and potassium nitrate.",
		Model = "models/props_lab/jar01b.mdl",
		Color = Color(255, 0, 0),
		Weight = 0.1,
		LootType = { },
		Price = 15,	
		Credits = 1,
		SpawnChance = -1,
		SpawnOffset = Vector(0,0,4),
		UsedInCrafting = true,	
		EatFunction = function(ply, item) ply:EatHurt(5, 50) end,	
	},

	{
		ID = "item_gunpowder_proc",
		Name = "Processed Gunpowder",
		Angle = Angle(0,0,0),
		Desc = "A mixture of sulfur, charcoal and potassium nitrate.",
		Model = "models/props_lab/jar01a.mdl",
		Color = Color(150, 150, 150),
		Weight = 0.5,
		LootType = {},
		Price = 30,	
		Credits = 3,
		SpawnChance = -1,
		SpawnOffset = Vector(0,0,4),
		UsedInCrafting = true,
		Craftable = true,
		ReqCraft = { Slot1 = "item_gunpowder", Slot2="item_gunpowder", Slot3="item_gunpowder", Slot4="item_gunpowder", Slot5="item_gunpowder" },	
		EatFunction = function(ply, item) ply:EatHurt(5, 50) end,	
	},

	{
		ID = "item_gunpowder_ref",
		Name = "Refined Gunpowder",
		Angle = Angle(0,0,0),
		Desc = "A mixture of sulfur, charcoal and potassium nitrate.",
		Model = "models/props_lab/jar01a.mdl",
		Color = Color(50, 50, 50),
		Weight = 2.5,
		LootType = { },
		Price = 60,	
		Credits = 6,
		SpawnChance = -1,
		SpawnOffset = Vector(0,0,4),
		Craftable = true,
		UsedInCrafting = true,
		ReqCraft = { Slot1 = "item_gunpowder_proc", Slot2="item_gunpowder_proc", Slot3="item_gunpowder_proc", Slot4="item_gunpowder_proc", Slot5="item_gunpowder_proc" },
		EatFunction = function(ply, item) ply:EatHurt(5, 50) end,	
	},

	{
		ID = "item_fuse",
		Name = "Fuse",
		Angle = Angle(0,0,0),
		Desc = "Short, like a certain Scottish man's temper.",
		Model = "models/gibs/furniture_gibs/furniture_chair01a_gib02.mdl",
		Weight = 0.3,
		LootType = { },
		Price = 30,	
		Credits = 3,
		SpawnChance = -1,
		Craftable = true,
		UsedInCrafting = true,
		ReqCraft = { Slot1 = "item_plantfibre", Slot2="item_plantfibre", Slot3="item_plantfibre", Slot4="item_plantfibre", Slot5="item_plantfibre" },
		SpawnOffset = Vector(0,0,4),		
		EatFunction = function(ply, item) ply:EatHurt(5, 50) end,	
	},

	{
		ID = "item_plantfibre",
		Name = "Plant Fibre",
		Angle = Angle(0,0,0),
		Desc = "Not to be mistaken for Special K.",
		Model = "models/gibs/antlion_gib_small_1.mdl",
		Color = Color(0, 255, 0),
		Material = "models/props_c17/FurnitureMetal001a",
		Weight = 0.1,
		LootType = { },
		Price = 30,	
		Credits = 3,
		SpawnChance = -1, -- Out of 100
		Craftable = true,
		UsedInCrafting = true,
		ReqCraft = { Slot1 = "item_cactus" },
		SpawnOffset = Vector(0,0,4),
		EatFunction = function(ply, item) ply:EatHurt(5, 50) end,	
	},

	{
		ID = "item_hula",
		Name = "Hula Doll",
		Angle = Angle(0,0,0),
		Desc = "I wonder where this has been?",
		Model = "models/props_lab/huladoll.mdl",
		Weight = 1,
		LootType = { "Basic" },
		Price = 15,	
		Credits = 1,
		SpawnChance = 55,
		SpawnOffset = Vector(0,0,3),
		EatFunction = function(ply, item) ply:EatHurt(5, 50) end,			
	},

	{
		ID = "item_book",
		Name = "A Book",
		Angle = Angle(0,0,0),
		Desc = "A story of the life of Ruben Van Schaik",
		Model = "models/props_lab/binderblue.mdl",
		Weight = 1,
		LootType = { "Basic" },
		Price = 15,	
		Credits = 1,
		SpawnChance = 55,
		SpawnOffset = Vector(0,0,3),	
		EatFunction = function(ply, item) ply:EatHurt(5, 50) end,	
	},	

	{
		ID = "item_emptycan",
		Name = "Empty Can",
		Angle = Angle(0,0,0),
		Desc = "Life is like this tin can: Empty.",
		Model = "models/props_junk/garbage_metalcan002a.mdl",
		Weight = 1,
		LootType = { "Basic" },
		Price = 15,	
		Credits = 1,
		SpawnChance = 55, -- Out of 100
		SpawnOffset = Vector(0,0,3),
		UsedInCrafting = true,
		EatFunction = function(ply, item) ply:EatHurt(5, 50) end,	
	},

	{
		ID = "item_cactus",
		Name = "A cactus",
		Angle = Angle(0,0,0),
		Desc = "Prickly.",
		Model = "models/props_lab/cactus.mdl",
		Weight = 1,
		LootType = { "Basic" },
		Price = 15,	
		Credits = 1,
		SpawnChance = 55,
		UsedInCrafting = true,
		Decompiles = { "item_plantfibre" },
		SpawnOffset = Vector(0,0,3),
		EatFunction = function(ply, item) ply:EatHurt(5, 50) end,	
	},

	{
		ID = "item_irnbru",
		Name = "Irn Bru",
		Angle = Angle(0,0,0),
		Desc = "Scotland's other National Drink",
		Model = "models/props_cans/irnbru01a.mdl",
		Weight = 1,
		LootType = { "Food" },
		Price = 125,	
		Credits = 12,
		SpawnChance = 35,
		SpawnOffset = Vector(0,0,3.5),
		DrinkFunction = function(ply, item) ply:Drink(25) ply:GiveStamina(30) end,		
	},

	{
		ID = "item_metalcan",
		Name = "Can of beans",
		Angle = Angle(0,0,0),
		Desc = "Eat this to restore hunger.",
		Model = "models/props_junk/garbage_metalcan001a.mdl",
		Weight = 1,
		LootType = { "Food" },
		Price = 30,
		Credits = 3,
		SpawnChance = 75, -- Out of 100
		SpawnOffset = Vector(0,0,3.5),
		EatFunction = function(ply, item) ply:Eat(15) ply:GiveItem("item_emptycan", 1) end,			
	},	

	{
		ID = "item_drink2",
		Name = "Beer",
		Angle = Angle(0,0,0),
		Desc = "Overindulgence may result in death.",
		Model = "models/props_junk/GlassBottle01a.mdl",
		Weight = 1,
		LootType = { "Food" },
		Price = 75,	
		Credits = 7,
		SpawnChance = 60, -- Out of 100
		SpawnOffset = Vector(0,0,9),
		DrinkFunction = function(ply, item) ply:Drink(25) end,		
	},

	{
		ID = "item_drink3",
		Name = "Old Milk",
		Angle = Angle(0,0,0),
		Desc = "Drink this to quench your thirst.",
		Model = "models/props_junk/garbage_milkcarton002a.mdl",
		Weight = 1,
		LootType = { "Food" },
		Price = 10,		
		Credits = 1,
		SpawnChance = 40, -- Out of 100
		SpawnOffset = Vector(0,0,8),
		DrinkFunction = function(ply, item) ply:Drink(10) end,		
	},

	{
		ID = "item_food1",
		Name = "Stale Take-away",
		Angle = Angle(0,0,0),
		Desc = "Eat this to restore hunger.",
		Model = "models/props_junk/garbage_takeoutcarton001a.mdl",
		Weight = 1,
		LootType = { "Food" },
		Price = 25,	
		Credits = 2,
		SpawnChance = 90, -- Out of 100
		SpawnOffset = Vector(0,0,6),
		EatFunction = function(ply, item) ply:Eat(25) end,		
	},

	{
		ID = "item_food2",
		Name = "Melon",
		Angle = Angle(0,0,0),
		Desc = "Eat this to restore a little hunger/thirst.",
		Model = "models/props_junk/watermelon01.mdl",
		Weight = 1,
		Price = 30,		
		Credits = 3,
		LootType = { "Food" },
		SpawnChance = 55, -- Out of 100
		SpawnOffset = Vector(0,0,7),
		EatFunction = function(ply, item) ply:Eat(35) ply:Drink(10) end,		
	},

	{
		ID = "item_food3",
		Name = "Banana",
		Angle = Angle(0,0,0),
		Desc = "Variety of applications.",
		Model = "models/props/cs_italy/bananna.mdl",
		Weight = 1,
		LootType = { "Food" },
		Price = 30,	
		Credits = 3,
		SpawnChance = 57, -- Out of 100
		SpawnOffset = Vector(0,0,3),
		EatFunction = function(ply, item) ply:Eat(15) end,		
	},

	{
		ID = "item_food3bunch",
		Name = "Banana Bunch",
		Angle = Angle(0,0,0),
		Desc = "Multitude of applications with spares.",
		Model = "models/props/cs_italy/bananna_bunch.mdl",
		Weight = 1,
		LootType = { "Food" },
		Price = 60,	
		Credits = 6,
		SpawnChance = 57, -- Out of 100
		SpawnOffset = Vector(0,0,3),
		EatFunction = function(ply, item) ply:Eat(35) end,		
	},

	{
		ID = "item_potato",
		Name = "Potato",
		Angle = Angle(0,0,0),
		Desc = "Food for the Irish.",
		Model = "models/props_phx/misc/potato.mdl",
		Weight = 1,
		LootType = { "Food" },
		Price = 30,	
		Credits = 3,
		SpawnChance = 65, -- Out of 100
		SpawnOffset = Vector(0,0,3),
		EatFunction = function(ply, item) ply:Eat(35) end,		
	},

	{
		ID = "item_food4",
		Name = "Orange",
		Angle = Angle(0,0,0),
		Desc = "I'm in the middle of no- Ooh an orange.",
		Model = "models/props/cs_italy/orange.mdl",
		Weight = 1,
		LootType = { "Food" },
		Price = 30,	
		Credits = 3,
		SpawnChance = 65, -- Out of 100
		SpawnOffset = Vector(0,0,3),
		EatFunction = function(ply, item) ply:Eat(35) end,		
	},

	{
		ID = "item_food5",
		Name = "Fish",
		Angle = Angle(0,0,2),
		Desc = "Eat this to restore hunger.",
		Model = "models/props/cs_militia/fishriver01.mdl",
		Weight = 1,
		Price = 30,
		Credits = 3,
		LootType = { "Food" },
		SpawnChance = 50, -- Out of 100
		SpawnOffset = Vector(0,0,1),
		SpawnAngle = Angle(0,0,90),		
		EatFunction = function(ply, item) ply:Eat(10) end,		
	},

	{
		ID = "item_bleach",
		Name = "Bleach",
		Angle = Angle(0,0,2),
		Desc = "The label reads: Keep out of reach of children.",
		Model = "models/props_junk/garbage_plasticbottle002a.mdl",
		Weight = 1,
		Price = 30,
		Credits = 3, 
		LootType = { "Food", "Industrial" },
		SpawnChance = 50, -- Out of 100
		SpawnOffset = Vector(0,0,1),
		SpawnAngle = Angle(0,0,90),		
		DrinkFunction = function(ply, item) ply:DrinkHurt(15, 35) end,		
	},
		
	{
		ID = "item_medic1",
		Name = "Painkillers",
		Angle = Angle(0,0,2),
		Desc = "Household painkillers for treating aches.",
		Model = "models/w_models/weapons/w_eq_painpills.mdl",
		Weight = 1,
		LootType = { "Medical" },
		Price = 40,
		Credits = 4,
		SpawnChance = 50,
		UsedInCrafting = true,
		SpawnOffset = Vector(0,0,0),
		Function = function(ply, item) ply:Heal(20) end,			
	},

	{
		ID = "item_medic2",
		Name = "Bandages",
		Angle = Angle(0,0,2),
		Desc = "Army issue medicinal gauzes.",
		Model = "models/w_models/weapons/w_eq_medkit.mdl",
		Weight = 1,
		LootType = { "Medical" },
		Price = 100,
		Credits = 10,	
		SpawnChance = 15, -- Out of 100
		SpawnOffset = Vector(0,0,0),
		Craftable = true,
		ReqCraft = { Slot1 = "item_fabric", Slot2="item_aloecream", Slot3="item_fabric" },
		Function = function(ply, item) ply:Heal(55) end,		
	},

	{
		ID = "item_aloecream",
		Name = "AloeCream",
		Angle = Angle(0,0,2),
		Desc = "Medical balm for treating lacerations.",
		Model = "models/props_junk/glassjug01.mdl",
		Weight = 1,
		LootType = { "Medical" },
		Price = 60,
		Credits = 6,	
		Craftable = true,
		UsedInCrafting = true,
		SpawnChance = 25, -- Out of 100
		SpawnOffset = Vector(0,0,0),
		Function = function(ply,item) ply:Heal(30) end,		
	},	

	{
		ID = "item_grenade",
		Name = "Grenade",
		Angle = Angle(90,90,90), 
		Desc = "Uh oh.",
		Model = "models/weapons/w_eq_fraggrenade_thrown.mdl",
		Weight = 10,
		Price = 800,
		Credits = 80,
		SpawnChance = 1, -- Out of 100		
		SpawnOffset = Vector(0,0,1),
		SpawnAngle = Angle(0,0,90),		
		LootType = { "Weapon" },
		Gun = true,
		Primary = true,
		Craftable = true,
		ReqCraft = { Slot1="item_fuse", Slot2="item_gunpowder_ref", Slot3="item_soddenrag", Slot4="item_emptycan" },
		Weapon = "weapon_grenade",
		EatFunction = function(ply, item) ply:EatHurt(5, 50) end,	
	},

	
	{
		ID = "item_deagle",
		Name = "Desert Eagle",
		Angle = Angle(90,90,90), 
		Desc = "A Desert Eagle chambered in .50 Action Express.",
		Model = "models/weapons/w_pist_deagle.mdl",
		Weight = 30,
		Price = 1200,
		Credits = 120,
		SpawnChance = 5, -- Out of 100		
		SpawnOffset = Vector(0,0,1),
		SpawnAngle = Angle(0,0,90),		
		LootType = { "Weapon" },
		Gun = true,
		Secondary = true,
		Craftable = true,
		ReqCraft = { Slot3 = "item_part_g", Slot4 = "item_part_c" },
		Weapon = "swb_secondary_deagle",
		EatFunction = function(ply, item) ply:EatHurt(5, 50) end,	
	},
	
	{
		ID = "item_fiveseven",
		Name = "Five Seven",
		Angle = Angle(90,90,90), 
		Desc = "An FN 5-7, chambered in custom 5.7×28mm.",
		Model = "models/weapons/w_pist_fiveseven.mdl",
		Weight = 30,
		Price = 1200,
		Credits = 120,
		SpawnChance = 5, -- Out of 100		
		SpawnOffset = Vector(0,0,1),
		SpawnAngle = Angle(0,0,90),		
		LootType = { "Weapon" },
		Gun = true,
		Secondary = true,
		Craftable = true,
		ReqCraft = { Slot2="item_part_g", Slot4="item_part_d" },
		Weapon = "swb_secondary_fiveseven",
		EatFunction = function(ply, item) ply:EatHurt(5, 50) end,
	},
	
	{
		ID = "item_swb_ragingbull", -- RENAME LATER
		Name = "Raging Bull",
		Angle = Angle(90,90,90), 
		Desc = "A six shooter chambered in .454 Casull, heads will roll.",
		Model = "models/weapons/w_357.mdl",
		Weight = 30,
		Price = 1200,
		Credits = 120,
		SpawnChance = 4, -- Out of 100		
		SpawnOffset = Vector(0,0,1),
		SpawnAngle = Angle(0,0,90),		
		LootType = { "Weapon" },
		Gun = true,
		Secondary = true,
		Craftable = true,
		ReqCraft = { Slot1="item_part_b", Slot2="item_part_f" },
		Weapon = "swb_secondary_357",
		EatFunction = function(ply, item) ply:EatHurt(5, 50) end,	
	},

	{
		ID = "item_ak47",
		Name = "AK47",
		Angle = Angle(90,90,90), 
		Desc = "Avtomat Kalashnikova chambered in 7.62x39mm.",
		Model = "models/weapons/w_rif_ak47.mdl",
		Weight = 40,
		Price = 1400,
		Credits = 140,
		SpawnChance = 3, -- Out of 100		
		SpawnOffset = Vector(0,0,1),
		SpawnAngle = Angle(0,0,90),		
		LootType = { "Weapon" },
		Gun = true,
		Primary = true, 
		Craftable = true,
		ReqCraft = { Slot2="item_part_a", Slot3="item_part_d", Slot5="item_part_c" },
		Weapon = "swb_primary_ak47",
		EatFunction = function(ply, item) ply:EatHurt(5, 50) end,	
	},
	
	{
		ID = "item_swb_g3sg1",
		Name = "H&K G3SG1",
		Angle = Angle(90,90,90), 
		Desc = "H&K G3, chambered in 7.62x51mm NATO.",
		Model = "models/weapons/w_snip_g3sg1.mdl",
		Weight = 40,
		Price = 1400,
		Credits = 140,
		SpawnChance = 2, -- Out of 100		
		SpawnOffset = Vector(0,0,1),
		SpawnAngle = Angle(0,0,90),		
		LootType = { "Weapon" },
		Gun = true,
		Primary = true, 
		Craftable = true,
		ReqCraft = { Slot1="item_part_a", Slot4="item_part_e", Slot5="item_part_f" },
		Weapon = "swb_primary_g3sg1",
		EatFunction = function(ply, item) ply:EatHurt(5, 50) end,	
	},
	
	{
		ID = "item_swb_m4a1",
		Name = "M4A1",
		Angle = Angle(90,90,90), 
		Desc = "M4 Carbine chambered in 5.56×45mm NATO.",
		Model = "models/weapons/w_rif_m4a1.mdl",
		Weight = 40,
		Price = 1400,
		Credits = 140,
		SpawnChance = 3, -- Out of 100		
		SpawnOffset = Vector(0,0,1),
		SpawnAngle = Angle(0,0,90),		
		LootType = { "Weapon" },
		Gun = true,
		Primary = true, 
		Craftable = true,
		ReqCraft = { Slot3="item_part_a", Slot4="item_part_b", Slot5="item_part_d" },
		Weapon = "swb_primary_m4a1",
		EatFunction = function(ply, item) ply:EatHurt(5, 50) end,	
	},
	
	{
		ID = "item_m3super90",
		Name = "Remington 887",
		Angle = Angle(90,90,90), 
		Desc = "A Remington 887 suited for 12 Gauge shells.",
		Model = "models/weapons/w_shot_m3super90.mdl",
		Weight = 40,
		Price = 1400,
		Credits = 140,
		SpawnChance = 2, -- Out of 100		
		SpawnOffset = Vector(0,0,1),
		SpawnAngle = Angle(0,0,90),		
		LootType = { "Weapon" },
		Gun = true,
		Primary = true, 
		Craftable = true,
		ReqCraft = { Slot2="item_part_c", Slot3="item_part_b", Slot4="item_part_a", Slot5="item_part_e" },
		Weapon = "swb_primary_m3super90",
		EatFunction = 
			function(ply,item)
				ply:EatHurt(5, 50)
			end,	
	},
	
	{
		ID = "item_swb_famas",
		Name = "FAMAS",
		Angle = Angle(90,90,90), 
		Desc = "A FAMAS chambered in 5.56×45mm NATO.",
		Model = "models/weapons/w_rif_famas.mdl",
		Weight = 40,
		Price = 1400,
		Credits = 140,
		SpawnChance = 3, -- Out of 100		
		SpawnOffset = Vector(0,0,1),
		SpawnAngle = Angle(0,0,90),		
		LootType = { "Weapon" },
		Gun = true,
		Primary = true, 
		Craftable = true,
		ReqCraft = { Slot1="item_part_a", Slot2="item_part_d", Slot4="item_part_g" },
		Weapon = "swb_primary_famas",
		EatFunction = function(ply, item) ply:EatHurt(5, 50) end,	
	},
	
	{
		ID = "item_swb_glock18",
		Name = "Glock 18",
		Angle = Angle(90,90,90), 
		Desc = "A Glock chambered in 9x19mm Parabellum.",
		Model = "models/weapons/w_pist_glock18.mdl",
		Weight = 20,
		Price = 1200,
		Credits = 120,
		SpawnChance = 5, -- Out of 100		
		SpawnOffset = Vector(0,0,1),
		SpawnAngle = Angle(0,0,90),		
		LootType = { "Weapon" },
		Gun = true,
		Secondary = true,
		Craftable = true,
		ReqCraft = { Slot2="item_part_g", Slot3="item_part_e" },
		Weapon = "swb_secondary_glock18",
		EatFunction = function(ply,item) ply:EatHurt(5, 50) end,	
	},
	
	{
		ID = "item_swb_scout",
		Name = "Steyr Scout",
		Angle = Angle(90,90,90), 
		Desc = "A Steyr Scout loading 5 round box mags of 3.31x34mm.",
		Model = "models/weapons/w_snip_scout.mdl",
		Weight = 40,
		Price = 1800,
		Credits = 180,
		SpawnChance = 2, -- Out of 100		
		SpawnOffset = Vector(0,0,1),
		SpawnAngle = Angle(0,0,90),		
		LootType = { "Weapon" },
		Gun = true,
		Primary = true, 
		Craftable = true,
		ReqCraft = { Slot3="item_part_a", Slot4="item_part_e", Slot5="item_part_g" },
		Weapon = "swb_primary_scout",
		EatFunction = function(ply, item) ply:EatHurt(5, 50) end,	
	},
	
	{
		ID = "item_awp",
		Name = "Accuracy International AW",
		Angle = Angle(90,90,90), 
		Desc = "An Accuracy International Arctic Warfare chambered in .308 Winchester.",
		Model = "models/weapons/w_snip_awp.mdl",
		Weight = 50,
		Price = 2400,
		Credits = 240,
		SpawnChance = 1, -- Out of 100		
		SpawnOffset = Vector(0,0,1),
		SpawnAngle = Angle(0,0,90),		
		LootType = { "Weapon" },
		Gun = true,
		Primary = true, 
		Craftable = true,
		ReqCraft = { Slot1="item_part_a", Slot2="item_part_c", Slot3="item_part_e", Slot4="item_part_f", Slot5="item_part_h" },
		Weapon = "swb_primary_awp",
		EatFunction = function(ply, item) ply:EatHurt(5, 50) end,	
	},

	{
		ID = "item_ammo_glock18",
		Name = "Box of 9x19mm Parabellum Rounds.",
		Angle = Angle(90,90,90), 
		Desc = "9x19mm Parabellum Rounds.",-- The description
		Model = "models/Items/BoxMRounds.mdl",
		Weight = 0.01,
		Price = 360,
		Credits = 18,
		SpawnChance = 15, -- Out of 1300	
		SpawnOffset = Vector(0,0,1),		
		LootType = { "Weapon" },
		ClipSize = 18, -- 20 a bullet
		AmmoType = "pistol",
		UsedInCrafting = true, 
		Craftable = true, 
		Decompiles = { "item_gunpowder" },
		ReqCraft = { Slot1="item_gunpowder", Slot2="item_gunpowder" },
	},
	
	{
		ID = "item_ammo_ragingbull",
		Name = "Box of .454 Casull.",
		Angle = Angle(90,90,90), 
		Desc = ".454 Casull Magnum Rounds.",-- The description
		Model = "models/items/357ammobox.mdl",
		Color = Color(255, 0, 0, 255),
		Weight = 0.01,
		Price = 360, -- 20 a bullet
		Credits = 18,
		SpawnChance = 15, -- Out of 100	
		SpawnOffset = Vector(0,0,1),		
		LootType = { "Weapon" },
		UsedInCrafting = true, 
		Craftable = true, 
		Decompiles = { "item_gunpowder" },
		ReqCraft = { Slot1="item_gunpowder", Slot2="item_gunpowder" },
		ClipSize = 6,
		AmmoType = "357",
	},

	{
		ID = "item_ammo_fiveseven",
		Name = "Box of 5.7×28mm rounds.",
		Angle = Angle(90,90,90), 
		Desc = "5.7×28mm rounds.",-- The description
		Model = "models/items/357ammobox.mdl",
		Color = Color(0, 255, 0, 255),
		Weight = 0.01,
		Price = 360, -- 20 a bullet
		Credits = 18,
		SpawnChance = 15, -- Out of 100	
		SpawnOffset = Vector(0,0,1),		
		LootType = { "Weapon" },
		ClipSize = 18,
		AmmoType = "Battery",
		UsedInCrafting = true, 
		Craftable = true, 
		Decompiles = { "item_gunpowder" },
		ReqCraft = { Slot1="item_gunpowder", Slot2="item_gunpowder" },
	},

	{
		ID = "item_ammo_deagle",
		Name = ".50 Action Express.",
		Angle = Angle(90,90,90), 
		Desc = ".50 Caliber Rounds for the Desert Eagle.",-- The description
		Model = "models/items/357ammobox.mdl",
		Color = Color(0, 0, 255, 255),
		Weight = 0.01,
		Price = 210, -- 30 a bullet
		Credits = 10,
		SpawnChance = 15, -- Out of 100	
		SpawnOffset = Vector(0,0,1),		
		LootType = { "Weapon" },
		ClipSize = 7,
		AmmoType = "StriderMinigun",
		UsedInCrafting = true, 
		Craftable = true, 
		Decompiles = { "item_gunpowder" },
		ReqCraft = { Slot1="item_gunpowder", Slot2="item_gunpowder" },
	},
	
	{
		ID = "item_ammo_ak47",
		Name = "Box of 7.62x39mm",
		Angle = Angle(90,90,90), 
		Desc = "7.62x39mm FMJ Rounds.",-- The description
		Model = "models/Items/BoxSRounds.mdl",
		Weight = 0.01,
		Price = 600, -- 20 a bullet
		Credits = 30,
		SpawnChance = 30, -- Out of 100	
		SpawnOffset = Vector(0,0,1),		
		LootType = { "Weapon" },
		ClipSize = 30,
		AmmoType = "ar2",
		UsedInCrafting = true, 
		Craftable = true, 
		Decompiles = { "item_gunpowder" },
		ReqCraft = { Slot1="item_gunpowder", Slot2="item_gunpowder", Slot3="item_gunpowder" },
	},
	
	{
		ID = "item_ammo_m3super90",
		Name = "12 Gauge Shells.",
		Angle = Angle(90,90,90), 
		Desc = "Shotgun Shells.",-- The description
		Model = "models/Items/BoxBuckshot.mdl",
		Weight = 0.01,
		Price = 400,
		Credits = 20,
		SpawnChance = 30, -- Out of 100	
		SpawnOffset = Vector(0,0,1),		
		LootType = { "Weapon" },
		ClipSize = 8, -- 50 a bullet
		AmmoType = "buckshot",
		UsedInCrafting = true, 
		Craftable = true, 
		Decompiles = { "item_gunpowder" },
		ReqCraft = { Slot1="item_gunpowder", Slot2="item_gunpowder", Slot3="item_gunpowder" },
	},
	
	{
		ID = "item_ammo_famas",
		Name = "Box of 5.56x45mm NATO.",
		Angle = Angle(90,90,90), 
		Desc = "5.56x45mm NATO rounds.",-- The description
		Model = "models/Items/BoxSRounds.mdl",
		Color = Color(255, 255, 0, 255),
		Weight = 0.01,
		Price = 600, -- 30 a bullet
		Credits = 30,
		SpawnChance = 30, -- Out of 100	
		SpawnOffset = Vector(0,0,1),		
		LootType = { "Weapon" },
		ClipSize = 25,
		AmmoType = "SMG1",
		UsedInCrafting = true, 
		Craftable = true, 
		Decompiles = { "item_gunpowder" },
		ReqCraft = { Slot1="item_gunpowder", Slot2="item_gunpowder", Slot3="item_gunpowder" },
	},

	{
		ID = "item_ammo_awp",
		Name = "Box of .308 Winchester.",
		Angle = Angle(90,90,90), 
		Desc = ".308 Winchester rounds.",-- The description
		Model = "models/props/de_prodigy/ammo_can_02.mdl",
		Weight = 1,
		Price = 1000, -- 200 a bullet
		Credits = 50,
		SpawnChance = 10, -- Out of 100	
		SpawnOffset = Vector(0,0,1),		
		LootType = { "Weapon" },
		ClipSize = 5,
		AmmoType = "SniperRound",
		UsedInCrafting = true, 
		Craftable = true, 
		Decompiles = { "item_gunpowder_proc" },
		ReqCraft = { Slot1="item_gunpowder_proc", Slot2="item_gunpowder_proc" },
	},
	
	{
		ID = "item_ammo_scout",
		Name = "Box of .376 Steyr.",
		Angle = Angle(90,90,90), 
		Desc = ".376 Steyr Rounds.",-- The description
		Model = "models/Items/BoxMRounds.mdl",
		Color = Color(170, 0, 255, 255), 
		Weight = 0.1,
		Price = 600, -- 200 a bullet
		Credits = 30,
		SpawnChance = 10, -- Out of 100	
		SpawnOffset = Vector(0,0,1),		
		LootType = { "Weapon" },
		ClipSize = 10,
		AmmoType = "SniperPenetratedRound",
		UsedInCrafting = true, 
		Craftable = true, 
		Decompiles = { "item_gunpowder" },
		ReqCraft = { Slot1="item_gunpowder_proc", Slot2="item_gunpowder" },
	},
	
	{
		ID = "item_ammo_g3sg1",
		Name = "Box of 7.62×51mm NATO.",
		Angle = Angle(90,90,90), 
		Desc = "7.62×51mm NATO Rounds.",-- The description
		Model = "models/Items/BoxSRounds.mdl",
		Color = Color(0, 255, 0, 255),
		Weight = 0.5,
		Price = 600, -- 200 a bullet
		Credits = 30,
		SpawnChance = 10, -- Out of 100	
		SpawnOffset = Vector(0,0,1),		
		LootType = { "Weapon" },
		ClipSize = 20,
		AmmoType = "HelicopterGun",
		UsedInCrafting = true, 
		Craftable = true, 
		Decompiles = { "item_gunpowder" },
		ReqCraft = { Slot1="item_gunpowder_proc", Slot2="item_gunpowder" },
	},

	{
		ID = "item_part_a",
		Name = "Part A",
		Angle = Angle(90,90,90), 
		Desc = "A part for a weapon ??",
		Model = "models/props_junk/cardboard_box003a.mdl",
		Weight = 5,
		Price = 50,
		--Credits = 1,		
		SpawnChance = 10, -- Out of 100		
		UsedInCrafting = true,
		SpawnOffset = Vector(0,0,0),
		SpawnAngle = Angle(0,0,0),		
		LootType = { "Industrial", "Weapon" },
		EatFunction = function(ply, item) ply:EatHurt(5, 50) end,	
	},

	{
		ID = "item_part_b",
		Name = "Part B",
		Angle = Angle(90,90,90), 
		Desc = "A part for a weapon ??",
		Model = "models/props_junk/cardboard_box003a.mdl",
		Weight = 5,
		Price = 50,
		Credits = 5,		
		SpawnChance = 10, -- Out of 100		
		UsedInCrafting = true,
		SpawnOffset = Vector(0,0,0),
		SpawnAngle = Angle(0,0,0),		
		LootType = { "Industrial", "Weapon" },
		EatFunction = function(ply, item) ply:EatHurt(5, 50) end,	
	},

	{
		ID = "item_part_c",
		Name = "Part C",
		Angle = Angle(90,90,90), 
		Desc = "A part for a weapon ??",
		Model = "models/props_junk/cardboard_box003a.mdl",
		Weight = 5,
		Price = 50,
		Credits = 5,	
		SpawnChance = 10, -- Out of 100		
		UsedInCrafting = true,
		SpawnOffset = Vector(0,0,0),
		SpawnAngle = Angle(0,0,0),		
		LootType = { "Industrial", "Weapon" },
		EatFunction = function(ply, item) ply:EatHurt(5, 50) end,	
	},

	{
		ID = "item_part_d",
		Name = "Part D",
		Angle = Angle(90,90,90), 
		Desc = "A part for a weapon ??",
		Model = "models/props_junk/cardboard_box003a.mdl",
		Weight = 5,
		Price = 50,
		Credits = 5,		
		SpawnChance = 10, -- Out of 100		
		UsedInCrafting = true,
		SpawnOffset = Vector(0,0,0),
		SpawnAngle = Angle(0,0,0),		
		LootType = { "Industrial", "Weapon" },
		EatFunction = function(ply, item) ply:EatHurt(5, 50) end,	
	},

	{
		ID = "item_part_e",
		Name = "Part E",
		Angle = Angle(90,90,90), 
		Desc = "A part for a weapon ??",
		Model = "models/props_junk/cardboard_box003a.mdl",
		Weight = 5,
		Price = 50,
		Credits = 5,
		SpawnChance = 10, -- Out of 100		
		UsedInCrafting = true,
		SpawnOffset = Vector(0,0,0),
		SpawnAngle = Angle(0,0,0),		
		LootType = { "Industrial", "Weapon" },
		EatFunction = function(ply, item) ply:EatHurt(5, 50) end,	
	},

	{
		ID = "item_part_f",
		Name = "Part F",
		Angle = Angle(90,90,90), 
		Desc = "A part for a weapon ??",
		Model = "models/props_junk/cardboard_box003a.mdl",
		Weight = 5,
		Price = 50,
		Credits = 5,	
		SpawnChance = 10, -- Out of 100		
		UsedInCrafting = true,
		SpawnOffset = Vector(0,0,0),
		SpawnAngle = Angle(0,0,0),		
		LootType = { "Industrial", "Weapon" },
		EatFunction = function(ply, item) ply:EatHurt(5, 50) end,	
	},

	{
		ID = "item_part_g",
		Name = "Part G",
		Angle = Angle(90,90,90), 
		Desc = "A part for a weapon ??",
		Model = "models/props_junk/cardboard_box003a.mdl",
		Weight = 5,
		Price = 50,
		Credits = 5,	
		SpawnChance = 10, -- Out of 100		
		UsedInCrafting = true,
		SpawnOffset = Vector(0,0,0),
		SpawnAngle = Angle(0,0,0),		
		LootType = { "Industrial", "Weapon" },
		EatFunction = function(ply, item) ply:EatHurt(5, 50) end,	
	},

	{
		ID = "item_part_h",
		Name = "Part H",
		Angle = Angle(90,90,90), 
		Desc = "A part for a weapon ??",
		Model = "models/props_junk/cardboard_box003a.mdl",
		Weight = 10,
		Price = 50,
		Credits = 5,
		SpawnChance = 10, -- Out of 100		
		UsedInCrafting = true,
		SpawnOffset = Vector(0,0,0),
		SpawnAngle = Angle(0,0,0),		
		LootType = { "Industrial", "Weapon" },
		EatFunction = function(ply, item) ply:EatHurt(5, 50) end,	
	},
		
	{
		ID = "item_fabric",
		Name = "Fabric",
		Angle = Angle(90,90,90), 
		Desc = "Torn up clothes.",
		Model = "models/gibs/antlion_gib_small_2.mdl",
		Material = "models/props_c17/FurnitureMetal001a",
		Weight = 1,
		Price = 50,
		Credits = 5,		
		SpawnChance = 35, -- Out of 100		
		UsedInCrafting = true,
		SpawnOffset = Vector(0,0,0),
		SpawnAngle = Angle(0,0,0),		
		LootType = { "Industrial", "Weapon" },
		EatFunction = function(ply, item) ply:EatHurt(5, 20) end,	
	},	

	{
		ID = "item_soddenrag",
		Name = "Sodden Rag",
		Angle = Angle(90,90,90), 
		Desc = "Torn up clothes dunked in gas.",
		Model = "models/gibs/antlion_gib_small_2.mdl",
		Material = "models/props_c17/FurnitureMetal001a",
		Color = Color(75,75,75),
		Weight = 1,
		Price = 50,
		Credits = 5,		
		SpawnChance = -1, -- Out of 100	
		Craftable = true,
		ReqCraft = { Slot1="item_fabric", Slot2="item_gasoline" },	
		UsedInCrafting = true,
		SpawnOffset = Vector(0,0,0),
		SpawnAngle = Angle(0,0,0),		
		LootType = {},
		EatFunction = function(ply, item) ply:EatHurt(5, 20) end,	
	},

	{
		ID = "item_toolkit",
		Name = "Tool Kit",
		Angle = Angle(90,90,90), 
		Desc = "Used to Craft/Decompile Items.",
		Model = "models/props_c17/BriefCase001a.mdl",
		Weight = 5,
		Price = 50,
		Credits = 5,		
		SpawnChance = 30, -- Out of 100		
		SpawnOffset = Vector(0,0,0),
		SpawnAngle = Angle(0,0,0),		
		LootType = { "Industrial", "Weapon" },
		EatFunction = function(ply, item) ply:EatHurt(5, 50) end,	
	},
	
	{
		ID = "item_flashlight",
		Name = "Flashlight",
		Angle = Angle(90,90,90), 
		Desc = "Press [F] to use your flashlight.",
		Model = "models/raviool/flashlight.mdl",
		Weight = 1,
		Price = 50,
		Credits = 5,		
		SpawnChance = 70, -- Out of 100		
		SpawnOffset = Vector(0,0,0),
		SpawnAngle = Angle(0,0,0),		
		LootType = { "Industrial", "Weapon" },
		EatFunction = function(ply, item) ply:EatHurt(5, 25) end,	
	},

	{
		ID = "item_ghillie",
		Name = "Ghillie suit",
		Angle = Angle(90,90,90), 
		Desc = "Wear this to change your appearance.",
		Model = "models/props/cs_militia/footlocker01_closed.mdl",
		Weight = 1,
		Price = 200,
		Credits = 20,
		Decompiles = { "item_fabric" },
		SpawnChance = 10, -- Out of 100		
		SpawnOffset = Vector(0,0,10),
		Body = true,
		BodyModel = "models/combine_sniper.mdl", 
		SpawnAngle = Angle(0,0,0),		
		LootType = { "Industrial", "Weapon" },
		EatFunction = function(ply, item) ply:EatHurt(5, 50) end,		
	},

	{
		ID = "item_binoculars",
		Name = "Binoculars",
		Angle = Angle(0,0,0),
		Desc = "See things at a distance.",
		Model = "models/weapons/W_binoculars.mdl",
		Weight = 1,
		LootType = { "Industrial", "Weapon" },
		Price = 50,
		Credits = 5,		
		Secondary = true, 
		SpawnChance = 35, -- Out of 100
		SpawnOffset = Vector(0,0,0),
		Weapon = "weapon_binoculars",
		EatFunction = function(ply, item) ply:EatHurt(5, 50) end,	
	},

	{
		ID = "item_gasoline",
		Name = "Jerry can",
		Angle = Angle(90,90,90),
		Desc = "Used to fuel cars",
		Model = "models/props_junk/gascan001a.mdl",
		Price = 25,
		Credits = 2,
		Weight = 1,
		LootType = { "Industrial" },
		UsedInCrafting = true,
		SpawnChance = 35, -- Out of 100
		SpawnOffset = Vector(0,0,14),	
		DrinkFunction = function(ply, item) ply:DrinkHurt(5, 10) ply:Ignite(15) end,
		Function = 
			function(ply,item) 
			local tr = ply:GetEyeTrace()
			if tr.Entity:IsValid() then
				if tr.Entity.SeatOne then
				
					if tr.Entity.SeatOne:GetNWInt("fuel") + 20 <= 100 then
						tr.Entity.SeatOne:SetNWInt("fuel", tr.Entity.SeatOne:GetNWInt("fuel") + 20)
						ply:ChatPrint("Refueled for 20%")
					else
						tr.Entity.SeatOne:SetNWInt("fuel", 100)
						ply:ChatPrint("The fuel tank is now full")
					end	
					ply:EmitSound("ambient/water/water_spray1.wav",100,100)
					tr.Entity.SeatOne.GasCheck = CurTime()
				
				else
				
					if tr.Entity:GetNWInt("fuel") + 20 <= 100 then
						tr.Entity:SetNWInt("fuel", tr.Entity:GetNWInt("fuel") + 20)
						ply:ChatPrint("Refueled for 20%")
					else
						tr.Entity:SetNWInt("fuel", 100)
						ply:ChatPrint("The fuel tank is now full")
					end
					ply:EmitSound("ambient/water/water_spray1.wav",100,100)
					tr.Entity.GasCheck = CurTime()	
				end		
			end
			return false
		end,
	},

	{
		ID = "item_hat_1",
		Name = "Traffic Cone",
		Angle = Angle(-180,-90,-90),
		Desc = "Junk.",
		Model = "models/props_junk/TrafficCone001a.mdl",
		Price = 200,
		Credits = 20,
		Weight = 1,
		Hat = true,
		HatPos = Vector(0, 0, 0),
		HatAng = Angle(0, 0, 0),
		LootType = { "Hat" },
		SpawnChance = 1,
		SpawnOffset = Vector(0,0,5),	
		EatFunction = function(ply, item) ply:EatHurt(5, 50) end,
	},

	{
		ID = "item_hat_2",
		Name = "Bucket",
		Angle = Angle(-180,-90,-90),
		Desc = "Junk.",
		Model = "models/props_junk/MetalBucket01a.mdl",
		Price = 200,
		Credits = 20,
		Weight = 1,
		Hat = true,
		LootType = { "Hat" },
		SpawnChance = 1, -- Out of 100
		SpawnOffset = Vector(0,0,5),	
		EatFunction = function(ply, item) ply:EatHurt(5, 50) end,
	},

	{
		ID = "item_hat_3",
		Name = "Pot",
		Angle = Angle(-180,-90,-90),
		Desc = "Junk. Previous cooking utensil.",
		Model = "models/props_interiors/pot02a.mdl",
		Price = 200,
		Credits = 20,
		Weight = 1,
		Hat = true,
		HatPos = Vector(0, 0, 0),
		HatAng = Angle(0, 0, 0),
		LootType = { "Hat" },
		SpawnChance = 1, -- Out of 100
		SpawnOffset = Vector(0,0,5),	
		EatFunction = function(ply, item) ply:EatHurt(5, 50) end,
	},

	{
		ID = "item_hat_4",
		Name = "Cooking Pot",
		Angle = Angle(-180,-90,-90),
		Desc = "Junk. Previous cooking utensil.",
		Model = "models/props_c17/metalPot001a.mdl",
		Price = 200,
		Credits = 20,
		Weight = 1,
		Hat = true,
		HatPos = Vector(0, 0, 0),
		HatAng = Angle(0, 0, 0),
		LootType = { "Hat" },
		SpawnChance = 1,
		SpawnOffset = Vector(0,0,5),	
		EatFunction = function(ply, item) ply:EatHurt(5, 50) end,
	},

	{
		ID = "item_hat_5",
		Name = "Cap",
		Angle = Angle(-180,-90,-90),
		Desc = "Edible.",
		Model = "models/props/cs_office/Snowman_hat.mdl",
		Price = 200,
		Credits = 20,
		Weight = 1,
		Hat = true,
		VIP = true,
		HatPos = Vector(0, 0, 0),
		HatAng = Angle(0, 0, 0),
		LootType = { "Hat" },
		SpawnChance = 1,
		SpawnOffset = Vector(0,0,5),	
		EatFunction = function(ply, item) ply:EatHurt(5, 50) end,
	},

	{
		ID = "item_repairkit",
		Name = "Repair Kit",
		Angle = Angle(-180,-90,-90),
		Desc = "Used to repair vehicles.",
		Model = "models/props_c17/tools_wrench01a.mdl",
		Price = 200,
		Credits = 20,
		Weight = 1,
		LootType = { "Industrial", "Weapon" },
		SpawnChance = 15,
		SpawnOffset = Vector(0,0,5),	
		EatFunction = function(ply, item) ply:EatHurt(5, 50) end,
		Function = 
			function(ply,item) 
			local tr = ply:GetEyeTrace()
				if tr.Entity:IsValid() then
					if tr.Entity:Health() + 50 <= tr.Entity.MaxHP then
						tr.Entity:SetHealth(tr.Entity:Health() + 50)
						ply:ChatPrint("Repaired 50 points of damage.")
					else
						tr.Entity:SetHealth( tr.Entity.MaxHP )
						ply:ChatPrint("Vehicle fully repaired!")
					end
					ply:EmitSound("Water.ImpactSoft",100,100)

				end
				return false
			end,
	},

	{
		ID = "item_perk1",
		Name = "Cheetah",
		Angle = Angle(0,0,0),
		Desc = "Using this item permanently gives your character the ability to sprint for twice as far.",
		Model = "models/Combine_Helicopter/helicopter_bomb01.mdl",
		Weight = 0,
		Credits = 300,
		LootType = { "None" },
		SpawnChance = -1,
		SpawnOffset = Vector(0,0,3.5),
		Function = function(ply, item) ply:GivePerk(item) end,			
	},

	{
		ID = "item_perk2",
		Name = "Strong Back",
		Angle = Angle(0,0,0),
		Desc = "Using this item permanently gives your character the ability to carry double the normal weight amount.",
		Model = "models/Combine_Helicopter/helicopter_bomb01.mdl",
		Weight = 0,
		Credits = 700,
		LootType = { "None" },
		SpawnChance = -1,
		SpawnOffset = Vector(0,0,3.5),
		Function = function(ply, item) ply:GivePerk(item) end,			
	},

	{
		ID = "item_perk3",
		Name = "Dead Man's Luck",
		Angle = Angle(0,0,0),
		Desc = "Using this item permanently gives your character a chance of keeping some items on death.",
		Model = "models/Combine_Helicopter/helicopter_bomb01.mdl",
		Weight = 0,
		Credits = 1300,
		LootType = { "None" },
		SpawnChance = -1,
		SpawnOffset = Vector(0,0,3.5),
		Function = function(ply, item) ply:GivePerk(item) end,			
	},
		
	{
		ID = "item_perk4",
		Name = "Violent background",
		Angle = Angle(0,0,0),
		Desc = "Using this item permanently gives your character a crowbar on respawn.",
		Model = "models/Combine_Helicopter/helicopter_bomb01.mdl",
		Weight = 0,
		Credits = 550,
		LootType = { "None" },
		SpawnChance = -1,
		SpawnOffset = Vector(0,0,3.5),
		Function = function(ply, item) ply:GivePerk(item) end,			
	},

	{
		ID = "item_perk5",
		Name = "Zombie slayer",
		Angle = Angle(0,0,0),
		Desc = "Using this item permanently gives your character 50% more damage against zombies.",
		Model = "models/Combine_Helicopter/helicopter_bomb01.mdl",
		Weight = 0,
		Credits = 1500,
		LootType = { "None" },
		SpawnChance = -1,
		SpawnOffset = Vector(0,0,3.5),
		Function = function(ply, item) ply:GivePerk(item) end,			
	},

	{
		ID = "item_perk6",
		Name = "Enlightenment",
		Angle = Angle(0,0,0),
		Desc = "Never be without a flashlight again! Spawn with a flashlight.",
		Model = "models/Combine_Helicopter/helicopter_bomb01.mdl",
		Weight = 0,
		Credits = 150,
		LootType = { "None" },
		SpawnChance = -1,
		SpawnOffset = Vector(0,0,3.5),
		Function = function(ply, item) ply:GivePerk(item) end,			
	},

	{
		ID = "item_bankslot",
		Name = "+5 Bank Slots",
		Angle = Angle(0,0,0),
		Desc = "Using this item permanently gives your character 5 more slots in the bank.",
		Model = "models/Combine_Helicopter/helicopter_bomb01.mdl",
		Weight = 0,
		Credits = 500,
		Price = 5000,
		LootType = { "None" },
		SpawnChance = -1,
		SpawnOffset = Vector(0,0,3.5),
		Function = function(ply, item) ply:SetNWInt("extraslots", ply:GetNWInt("extraslots") + 5) ply:ChatPrint("You unlocked an extra 5 bank slots! You now have "..ply:GetNWInt("extraslots").." slots!") end,			
	}

} -- Fucking ballache.